New Tile Class and whatDoYourSnakeEyesSee method
kylebisley/starter-snake-python pull request #29
Opened 2020-03-05 21:11 UTC by DHervochon

Hasn't been tested but doesn't break anything, since nothing uses these yet.
Should be useful for cutting down time on pathfinding to food, and sets the foundation for panic mode.
Might want to move these into a classes file for Tile and parseBoard for snakeEyes.

2020-03-05 23:04 UTC, DimaMzk approved these changes

2020-03-05 23:04 UTC, DimaMzk commented on app/main.py
> +        x (integer): the x coordinate, should line up with our other methods
```suggestion
        x (int): the x coordinate, should line up with our other methods
```

2020-03-05 23:04 UTC, DimaMzk commented on app/main.py
> +        y (integer): the y coordinate etc
```suggestion
        y (int): the y coordinate etc
```

2020-03-05 23:04 UTC, DimaMzk commented on app/main.py
> +        visited (boolean): whether or not a tile has been visited, useful for some algorithms
```suggestion
        visited (bool): whether or not a tile has been visited, useful for some algorithms
```

2020-03-05 23:04 UTC, DimaMzk commented on app/main.py
> +        pathBoard (array): integer representation of current board
```suggestion
        pathBoard (list): integer representation of current board 
```

2020-03-05 23:04 UTC, DimaMzk commented on app/main.py
> +        xPos(int): the x coordinate of the tile we want to search from
```suggestion
        xPos (int): the x coordinate of the tile we want to search from
```

2020-03-05 23:04 UTC, DimaMzk commented on app/main.py
> +        yPos(int): the y coordinate of the tile we want to search from
```suggestion
        yPos (int): the y coordinate of the tile we want to search from
```

2020-03-06 00:31 UTC, AGuyNamedTate requested changes
Needs to pull changes from other branch. Currently breaks because of the printBoard function being moved to another file.

2020-03-06 00:58 UTC, AGuyNamedTate submitted a review, later dismissed

2020-03-06 01:01 UTC, AGuyNamedTate commented on app/main.py
> +    allBoardTiles = [[None for x in range(board_width)] for y in range(board_height)]
Please review variable name to reflect python naming conventions (all_board_tiles)

2020-03-06 01:08 UTC, AGuyNamedTate requested changes
Still requires rebase

2020-03-06 01:35 UTC, closed without merging